import React, { createContext, useContext, useState, useEffect } from "react";

export const translations = {
  en: {
    brandName: "PollPulse",
    tagline: "Real-Time Polling & Voting",
    heroBadge: "Real-Time Polling Platform with Anti-Duplicate Voting",
    heroTitle1: "Create Polls. Gather Voices.",
    heroTitle2: "Visualize Results Live.",
    heroDesc: "The all-in-one polling and decision-making platform. Launch customizable polls with dynamic expiry, instant QR code sharing, interactive visual charts, and strict duplicate vote prevention.",
    createPoll: "Create a Poll",
    explorePolls: "Explore Active Polls",
    trendingPolls: "Trending Polls",
    trendingDesc: "Most active discussions happening right now",
    viewAll: "View All",
    totalPolls: "Total Polls",
    votesCast: "Votes Cast",
    activeNow: "Active Now",
    registeredUsers: "Registered Users",
    noPollsFound: "No polls found. Be the first to create one!",
    whyChoose: "Engineered for High-Integrity Voting",
    whyDesc: "Everything needed to run transparent, engaging, and tamper-resistant polls.",
    antiDupTitle: "Anti-Duplicate Protection",
    antiDupDesc: "Database-level unique constraints ensure each voter casts only one verified vote per poll.",
    liveUpdatesTitle: "Live Real-Time Updates",
    liveUpdatesDesc: "Instant updates broadcast percentage changes immediately to all connected viewers.",
    chartsTitle: "Dynamic Visual Charts",
    chartsDesc: "Interactive Bar Charts, Donut Charts, and percentage trackers provide instant clarity.",
    qrTitle: "QR Code & Instant Sharing",
    qrDesc: "Generate QR codes and one-click shareable links for classrooms, presentations, and social media.",
    // Nav
    navExplore: "Explore",
    navCreate: "Create Poll",
    navDashboard: "Dashboard",
    navLogin: "Log In",
    navRegister: "Get Started",
    navLogout: "Log Out",
    // Explore
    exploreTitle: "Community Polls",
    exploreDesc: "Browse active discussions, vote on topics, and see what the world thinks.",
    searchPlaceholder: "Search polls by title or topic...",
    filterBy: "Filter By:",
    allPolls: "All Polls",
    activeOnly: "Active Only",
    closedExpired: "Closed / Expired",
    sortBy: "Sort By:",
    newestFirst: "Newest First",
    mostVoted: "Most Voted",
    expiringSoon: "Expiring Soon",
    // Categories
    catAll: "All",
    catTech: "Technology",
    catAI: "Artificial Intelligence",
    catCareer: "Career & Work",
    catGaming: "Gaming",
    catEntertainment: "Entertainment",
    catEducation: "Education",
    catSports: "Sports",
    catGeneral: "General",
    // Poll Details & Voting
    castYourVote: "Cast Your Vote",
    voteDistribution: "Vote Distribution",
    submitVote: "Submit Vote",
    logInToVote: "Log In to Vote",
    votedBanner: "Your vote has been recorded",
    yourChoice: "Your Choice",
    closedBadge: "Closed",
    expiredBadge: "Expired",
    noExpiry: "No Expiry",
    sharePoll: "Share",
    scanQR: "Scan to Vote on Mobile",
    copyLink: "Copy Link",
    copied: "Copied!",
    // Comments & Reactions
    discussion: "Community Discussion & Arguments",
    postComment: "Post Comment",
    commentPlaceholder: "Share your reasoning or debate this poll...",
    noComments: "No comments yet. Share your thoughts first!",
    like: "Like",
    reactions: "Community Reactions",
    exportData: "Export Results",
    downloadCSV: "Download CSV",
    downloadJSON: "Download JSON",
    bookmark: "Save Poll",
    bookmarked: "Saved",
    // Create Poll
    createHeading: "Create a Polling Campaign",
    createSubtitle: "Set up multiple options, customize voting rules, configure expiry, and share instantly.",
    pollDetailsStep: "1. Poll Details",
    questionLabel: "Question / Title",
    questionPlaceholder: "e.g. Which technology will dominate in 2026?",
    descLabel: "Description / Context (Optional)",
    descPlaceholder: "Add extra background, context, or voting rules...",
    categoryLabel: "Category",
    optionsStep: "2. Poll Options",
    addOption: "Add Another Option",
    minOptionsHint: "Min 2 options required",
    settingsStep: "3. Voting Settings",
    multiChoice: "Allow Multiple Choice",
    multiChoiceDesc: "Voters can select more than one option",
    expiryTitle: "Poll Expiration Date & Time",
    expiryDesc: "Automatically close poll when time runs out",
    privacyTitle: "Public vs Private",
    publicDesc: "Visible to anyone on the Explore feed",
    privateDesc: "Only accessible via direct link / secret passcode",
    publishBtn: "Publish Poll Campaign",
    // Dashboard
    myPolls: "My Created Polls",
    votedPolls: "Polls I Voted On",
    savedPolls: "Saved Bookmarks",
    totalVotesReceived: "Total Votes Received",
    participatedIn: "Polls Participated In"
  },
  hi: {
    brandName: "पोलपल्स",
    tagline: "रियल-टाइम वोटिंग और पोलिंग",
    heroBadge: "बिना डुप्लिकेट वोटिंग वाला सुरक्षित रियल-टाइम पोलिंग प्लेटफॉर्म",
    heroTitle1: "पोल बनाएं। राय एकत्र करें।",
    heroTitle2: "परिणाम लाइव देखें।",
    heroDesc: "एक संपूर्ण पोलिंग और निर्णय लेने का प्लेटफॉर्म। लाइव परिणाम, क्यूआर कोड शेयरिंग, इंटरैक्टिव चार्ट्स और मजबूत सुरक्षा के साथ पोल बनाएं।",
    createPoll: "नया पोल बनाएं",
    explorePolls: "सक्रिय पोल देखें",
    trendingPolls: "ट्रेंडिंग पोल",
    trendingDesc: "वर्तमान में सबसे लोकप्रिय चर्चाएं",
    viewAll: "सभी देखें",
    totalPolls: "कुल पोल",
    votesCast: "डाले गए वोट",
    activeNow: "वर्तमान सक्रिय",
    registeredUsers: "पंजीकृत उपयोगकर्ता",
    noPollsFound: "कोई पोल नहीं मिला। पहला पोल आप बनाएं!",
    whyChoose: "पारदर्शी और सुरक्षित वोटिंग के लिए निर्मित",
    whyDesc: "सुरक्षित, पारदर्शी और सटीक मतदान के लिए सभी आधुनिक सुविधाएं।",
    antiDupTitle: "डुप्लिकेट वोट रोकथाम",
    antiDupDesc: "डेटाबेस स्तर पर सुरक्षा यह सुनिश्चित करती है कि प्रत्येक उपयोगकर्ता केवल एक बार वोट दे सके।",
    liveUpdatesTitle: "लाइव अपडेट",
    liveUpdatesDesc: "हर वोट के साथ बिना पेज रीलोड किए तुरंत परिणाम अपडेट होते हैं।",
    chartsTitle: "सुंदर दृश्य चार्ट्स",
    chartsDesc: "बार चार्ट और डोनट चार्ट के साथ स्पष्ट प्रतिशत देखें।",
    qrTitle: "क्यूआर कोड शेयरिंग",
    qrDesc: "कक्षा, मीटिंग या सोशल मीडिया के लिए तुरंत स्कैन करने योग्य क्यूआर कोड प्राप्त करें।",
    navExplore: "एक्सप्लोर",
    navCreate: "पोल बनाएं",
    navDashboard: "डैशबोर्ड",
    navLogin: "लॉग इन",
    navRegister: "शुरू करें",
    navLogout: "लॉग आउट",
    exploreTitle: "समुदाय पोल",
    exploreDesc: "सक्रिय चर्चाएं ब्राउज़ करें, वोट दें और देखें कि लोग क्या सोचते हैं।",
    searchPlaceholder: "शीर्षक या विषय द्वारा पोल खोजें...",
    filterBy: "फ़िल्टर करें:",
    allPolls: "सभी पोल",
    activeOnly: "केवल सक्रिय",
    closedExpired: "समाप्त / बंद",
    sortBy: "क्रमबद्ध करें:",
    newestFirst: "नवीनतम पहले",
    mostVoted: "सर्वाधिक वोट",
    expiringSoon: "जल्द समाप्त होने वाले",
    catAll: "सभी",
    catTech: "प्रौद्योगिकी",
    catAI: "आर्टिफिशियल इंटेलिजेंस",
    catCareer: "करियर और काम",
    catGaming: "गेमिंग",
    catEntertainment: "मनोरंजन",
    catEducation: "शिक्षा",
    catSports: "खेल",
    catGeneral: "सामान्य",
    castYourVote: "अपना वोट डालें",
    voteDistribution: "वोट वितरण",
    submitVote: "वोट सबमिट करें",
    logInToVote: "वोट देने के लिए लॉग इन करें",
    votedBanner: "आपका वोट सफलतापूर्वक दर्ज कर लिया गया है",
    yourChoice: "आपकी पसंद",
    closedBadge: "बंद",
    expiredBadge: "समाप्त",
    noExpiry: "कोई समाप्ति नहीं",
    sharePoll: "शेयर करें",
    scanQR: "मोबाइल पर वोट करने के लिए स्कैन करें",
    copyLink: "लिंक कॉपी करें",
    copied: "कॉपी हो गया!",
    discussion: "सामुदायिक चर्चा और विचार",
    postComment: "टिप्पणी पोस्ट करें",
    commentPlaceholder: "अपनी राय या तर्क साझा करें...",
    noComments: "अभी तक कोई टिप्पणी नहीं है। पहली टिप्पणी आप करें!",
    like: "पसंद",
    reactions: "प्रतिक्रियाएं",
    exportData: "डेटा निर्यात",
    downloadCSV: "CSV डाउनलोड",
    downloadJSON: "JSON डाउनलोड",
    bookmark: "सेव करें",
    bookmarked: "सेव किया गया",
    createHeading: "नया पोल अभियान बनाएं",
    createSubtitle: "विकल्प जोड़ें, मतदान नियम सेट करें, समाप्ति समय चुनें और तुरंत शेयर करें।",
    pollDetailsStep: "१. पोल विवरण",
    questionLabel: "प्रश्न / शीर्षक",
    questionPlaceholder: "उदा. २०२६ में कौन सी तकनीक आगे रहेगी?",
    descLabel: "विवरण / संदर्भ (वैकल्पिक)",
    descPlaceholder: "अतिरिक्त पृष्ठभूमि या नियम जोड़ें...",
    categoryLabel: "श्रेणी",
    optionsStep: "२. पोल विकल्प",
    addOption: "एक और विकल्प जोड़ें",
    minOptionsHint: "न्यूनतम २ विकल्प आवश्यक",
    settingsStep: "३. वोटिंग सेटिंग्स",
    multiChoice: "बहु-विकल्प की अनुमति दें",
    multiChoiceDesc: "मतदाता एक से अधिक विकल्प चुन सकते हैं",
    expiryTitle: "समाप्ति तिथि और समय",
    expiryDesc: "समय समाप्त होने पर पोल स्वतः बंद हो जाएगा",
    privacyTitle: "सार्वजनिक बनाम निजी",
    publicDesc: "एक्सप्लोर फ़ीड पर सभी को दिखाई देगा",
    privateDesc: "केवल सीधे लिंक या पासकोड से सुलभ",
    publishBtn: "पोल प्रकाशित करें",
    myPolls: "मेरे द्वारा बनाए गए पोल",
    votedPolls: "जिन पोलों में मैंने वोट दिया",
    savedPolls: "सहेजे गए पोल",
    totalVotesReceived: "कुल प्राप्त वोट",
    participatedIn: "भाग लिए गए पोल"
  },
  te: {
    brandName: "పోల్‌పల్స్",
    tagline: "రియల్-టైమ్ పోలింగ్ & ఓటింగ్",
    heroBadge: "నకిలీ ఓట్లు లేని అత్యంత సురక్షితమైన రియల్-టైమ్ పోలింగ్ వేదిక",
    heroTitle1: "పోల్స్ సృష్టించండి. అభిప్రాయాలు పొందండి.",
    heroTitle2: "ఫలితాలను లైవ్‌గా చూడండి.",
    heroDesc: "అధునాతన పోలింగ్ మరియు నిర్ణయాత్మక వేదిక. లైవ్ ఫలితాలు, క్యూఆర్ కోడ్ షేరింగ్, ఇంటరాక్టివ్ గ్రాఫ్‌లు మరియు కఠినమైన డూప్లికేట్ ఓటింగ్ నివారణతో పోల్స్ ప్రారంభించండి.",
    createPoll: "పోల్ సృష్టించండి",
    explorePolls: "లైవ్ పోల్స్ చూడండి",
    trendingPolls: "ట్రెండింగ్ పోల్స్",
    trendingDesc: "ప్రస్తుతం జరుగుతున్న అత్యంత చురుకైన చర్చలు",
    viewAll: "అన్నీ చూడండి",
    totalPolls: "మొత్తం పోల్స్",
    votesCast: "నమోదైన ఓట్లు",
    activeNow: "ప్రస్తుతం లైవ్",
    registeredUsers: "నమోదిత వినియోగదారులు",
    noPollsFound: "పోల్స్ ఏవీ కనుగొనబడలేదు. మీరే మొదటి పోల్ సృష్టించండి!",
    whyChoose: "విశ్వసనీయ ఓటింగ్ కొరకు రూపకల్పన",
    whyDesc: "పారదర్శక, నిష్పాక్షిక ఓటింగ్ అనుభవం కోసం పూర్తి ఫీచర్లు.",
    antiDupTitle: "డూప్లికేట్ ఓటింగ్ నివారణ",
    antiDupDesc: "ఒక వినియోగదారు ఒకేసారి మాత్రమే ఓటు వేయగలిగేలా డేటాబేస్ భద్రత.",
    liveUpdatesTitle: "లైవ్ అప్‌డేట్స్",
    liveUpdatesDesc: "పేజీ రీఫ్రెష్ చేయకుండానే ఫలితాలు తక్షణమే ప్రత్యక్షంగా అప్‌డేట్ అవుతాయి.",
    chartsTitle: "ఆకర్షణీయమైన చార్ట్‌లు",
    chartsDesc: "బార్ చార్ట్ మరియు డోనట్ చార్ట్‌లతో ఫలితాలను సులభంగా విశ్లేషించండి.",
    qrTitle: "క్యూఆర్ కోడ్ & షేరింగ్",
    qrDesc: "మొబైల్ ఓటింగ్ కోసం తక్షణ క్యూఆర్ కోడ్ మరియు లింక్ షేరింగ్.",
    navExplore: "అన్వేషించండి",
    navCreate: "పోల్ సృష్టించండి",
    navDashboard: "డాష్‌బోర్డ్",
    navLogin: "లాగిన్",
    navRegister: "ప్రారంభించండి",
    navLogout: "లాగ్ అవుట్",
    exploreTitle: "కమ్యూనిటీ పోల్స్",
    exploreDesc: "వివిధ రంగాల పోల్స్ చూడండి, మీ ఓటు వేయండి.",
    searchPlaceholder: "శీర్షిక లేదా టాపిక్ ద్వారా వెతకండి...",
    filterBy: "ఫిల్టర్ చేయండి:",
    allPolls: "అన్ని పోల్స్",
    activeOnly: "యాక్టివ్ మాత్రమే",
    closedExpired: "ముగిసినవి",
    sortBy: "క్రమబద్ధీకరణ:",
    newestFirst: "సరికొత్తవి",
    mostVoted: "ఎక్కువ ఓట్లు వచ్చినవి",
    expiringSoon: "త్వరలో ముగిసేవి",
    catAll: "అన్నీ",
    catTech: "టెక్నాలజీ",
    catAI: "ఆర్టిఫిషియల్ ఇంటెలిజెన్స్",
    catCareer: "కెరీర్ & ఉద్యోగం",
    catGaming: "గేమింగ్",
    catEntertainment: "వినోదం",
    catEducation: "విద్య",
    catSports: "క్రీడలు",
    catGeneral: "సాధారణం",
    castYourVote: "మీ ఓటు వేయండి",
    voteDistribution: "ఓట్ల శాతం",
    submitVote: "ఓటు సమర్పించండి",
    logInToVote: "ఓటు వేయడానికి లాగిన్ అవ్వండి",
    votedBanner: "మీ ఓటు విజయవంతంగా నమోదైంది",
    yourChoice: "మీ ఎంపిక",
    closedBadge: "ముగిసింది",
    expiredBadge: "గడువు ముగిసింది",
    noExpiry: "గడువు లేదు",
    sharePoll: "షేర్ చేయండి",
    scanQR: "మొబైల్‌లో ఓటు వేయడానికి స్కాన్ చేయండి",
    copyLink: "లింక్ కాపీ చేయండి",
    copied: "కాపీ అయింది!",
    discussion: "కమ్యూనిటీ చర్చలు & వ్యాఖ్యలు",
    postComment: "వ్యాఖ్య పోస్ట్ చేయండి",
    commentPlaceholder: "మీ అభిప్రాయాన్ని లేదా కారణాన్ని ఇక్కడ రాయండి...",
    noComments: "ఇంకా వ్యాఖ్యలు లేవు. మీరే మొదటి వ్యాఖ్య రాయండి!",
    like: "లైక్",
    reactions: "ప్రతిస్పందనలు",
    exportData: "డేటా ఎగుమతి",
    downloadCSV: "CSV డౌన్‌లోడ్",
    downloadJSON: "JSON డౌన్‌లోడ్",
    bookmark: "సేవ్ చేయండి",
    bookmarked: "సేవ్ చేయబడింది",
    createHeading: "కొత్త పోలింగ్ క్యాంపెయిన్ సృష్టించండి",
    createSubtitle: "ఆప్షన్లు జోడించండి, నియమాలు సెట్ చేయండి మరియు షేర్ చేయండి.",
    pollDetailsStep: "1. పోల్ వివరాలు",
    questionLabel: "ప్రశ్న / శీర్షిక",
    questionPlaceholder: "ఉదా: 2026 లో అత్యుత్తమ టెక్నాలజీ ఏది?",
    descLabel: "వివరణ (ఐచ్ఛికం)",
    descPlaceholder: "మరిన్ని వివరాలు లేదా నియమాలు...",
    categoryLabel: "వర్గం",
    optionsStep: "2. పోల్ ఆప్షన్లు",
    addOption: "మరొక ఆప్షన్ జోడించండి",
    minOptionsHint: "కనీసం 2 ఆప్షన్లు అవసరం",
    settingsStep: "3. ఓటింగ్ సెట్టింగ్‌లు",
    multiChoice: "బహుళ ఎంపికను అనుమతించండి",
    multiChoiceDesc: "ఒకటి కంటే ఎక్కువ ఆప్షన్లను ఎంచుకోవచ్చు",
    expiryTitle: "గడువు తేదీ & సమయం",
    expiryDesc: "సమయం ముగిసిన తర్వాత పోల్ ఆటోమేటిక్‌గా ముగుస్తుంది",
    privacyTitle: "పబ్లిక్ వర్సెస్ ప్రైవేట్",
    publicDesc: "అందరికీ కనిపిస్తుంది",
    privateDesc: "లింక్ లేదా పాస్‌కోడ్ ఉన్నవారికే లభిస్తుంది",
    publishBtn: "పోల్ ప్రచురించండి",
    myPolls: "నేను సృష్టించిన పోల్స్",
    votedPolls: "నేను ఓటు వేసిన పోల్స్",
    savedPolls: "సేవ్ చేసిన పోల్స్",
    totalVotesReceived: "లభించిన మొత్తం ఓట్లు",
    participatedIn: "పాల్గొన్న పోల్స్"
  },
  ta: {
    brandName: "போல்பல்ஸ்",
    tagline: "நேரடி வாக்குப்பதிவு தளம்",
    heroBadge: "போலி வாக்குகள் இல்லாத பாதுகாப்பான வாக்குப்பதிவு",
    heroTitle1: "வாக்கெடுப்பு நடத்துங்கள்.",
    heroTitle2: "நேரடி முடிவுகளைக் காண்க.",
    heroDesc: "நவீன வாக்கெடுப்பு தளம். உடனடி முடிவுகள், கியூஆர் குறியீடு பகிர்வு மற்றும் சிறந்த வரைபடங்கள்.",
    createPoll: "வாக்கெடுப்பு உருவாக்குக",
    explorePolls: "வாக்கெடுப்புகளை காண்க",
    trendingPolls: "பிரபலமான வாக்கெடுப்புகள்",
    trendingDesc: "தற்போது தீவிரமாக நடைபெறும் விவாதங்கள்",
    viewAll: "அனைத்தும்",
    totalPolls: "மொத்த வாக்கெடுப்புகள்",
    votesCast: "பதிவான வாக்குகள்",
    activeNow: "நேரலையில் உள்ளவை",
    registeredUsers: "பயனர்கள்",
    noPollsFound: "வாக்கெடுப்புகள் எதுவும் இல்லை. நீங்களே ஒன்றை உருவாக்குங்கள்!",
    whyChoose: "பாதுகாப்பான வாக்கெடுப்பு",
    whyDesc: "துல்லியமான மற்றும் பாதுகாப்பான வாக்குப்பதிவு வசதிகள்.",
    antiDupTitle: "போலி வாக்கு தடுப்பு",
    antiDupDesc: "ஒருவர் ஒரு முறை மட்டுமே வாக்களிக்க முடியும்.",
    liveUpdatesTitle: "நேரடி அறிவிப்புகள்",
    liveUpdatesDesc: "உடனுக்குடன் திரையில் முடிவுகள் மாறும்.",
    chartsTitle: "வரைபடங்கள்",
    chartsDesc: "விளக்கமான வரைபடங்கள் மூலம் முடிவுகளைப் பாருங்கள்.",
    qrTitle: "QR குறியீடு",
    qrDesc: "மொபைலில் வாக்களிக்க QR குறியீட்டைப் பயன்படுத்துங்கள்.",
    navExplore: "ஆராய்க",
    navCreate: "உருவாக்குக",
    navDashboard: "முகப்பு",
    navLogin: "உள்நுழை",
    navRegister: "தொடங்குக",
    navLogout: "வெளியேறு",
    exploreTitle: "சமூக வாக்கெடுப்புகள்",
    exploreDesc: "விவாதங்களை ஆராய்ந்து வாக்களியுங்கள்.",
    searchPlaceholder: "தேடுங்கள்...",
    filterBy: "வடிகட்டு:",
    allPolls: "அனைத்தும்",
    activeOnly: "நேரலையில்",
    closedExpired: "முடிவடைந்தவை",
    sortBy: "வரிசைப்படுத்து:",
    newestFirst: "புதியவை",
    mostVoted: "அதிக வாக்குகள்",
    expiringSoon: "விரைவில் முடிபவை",
    catAll: "அனைத்தும்",
    catTech: "தொழில்நுட்பம்",
    catAI: "செயற்கை நுண்ணறிவு",
    catCareer: "தொழில் & பணி",
    catGaming: "விளையாட்டு",
    catEntertainment: "பொழுதுபோக்கு",
    catEducation: "கல்வி",
    catSports: "விளையாட்டுகள்",
    catGeneral: "பொதுவானவை",
    castYourVote: "வாக்களியுங்கள்",
    voteDistribution: "வாக்கு சதவீதம்",
    submitVote: "வாக்கை பதிவு செய்க",
    logInToVote: "வாக்களிக்க உள்நுழையவும்",
    votedBanner: "உங்கள் வாக்கு பதிவாகிவிட்டது",
    yourChoice: "உங்கள் தேர்வு",
    closedBadge: "முடிந்தது",
    expiredBadge: "காலாவதியானது",
    noExpiry: "கால வரம்பில்லை",
    sharePoll: "பகிர்க",
    scanQR: "மொபைலில் வாக்களிக்க ஸ்கேன் செய்க",
    copyLink: "இணைப்பை நகலெடு",
    copied: "நகலெடுக்கப்பட்டது!",
    discussion: "கருத்துகள் & விவாதங்கள்",
    postComment: "கருத்து பதிவிடுக",
    commentPlaceholder: "உங்கள் காரணத்தை எழுதுங்கள்...",
    noComments: "கருத்துகள் ஏதுமில்லை.",
    like: "விருப்பம்",
    reactions: "எதிர்வினைகள்",
    exportData: "பதிவிறக்கு",
    downloadCSV: "CSV பதிவிறக்கு",
    downloadJSON: "JSON பதிவிறக்கு",
    bookmark: "சேமி",
    bookmarked: "சேமிக்கப்பட்டது",
    createHeading: "புதிய வாக்கெடுப்பு",
    createSubtitle: "விருப்பங்களைச் சேர்த்து உடனே தொடங்குங்கள்.",
    pollDetailsStep: "1. விவரங்கள்",
    questionLabel: "கேள்வி",
    questionPlaceholder: "உங்கள் கேள்வி...",
    descLabel: "விளக்கம்",
    descPlaceholder: "கூடுதல் விளக்கம்...",
    categoryLabel: "பிரிவு",
    optionsStep: "2. விருப்பங்கள்",
    addOption: "விருப்பம் சேர்க்க",
    minOptionsHint: "குறைந்தது 2 விருப்பங்கள்",
    settingsStep: "3. அமைப்புகள்",
    multiChoice: "பல விருப்ப தேர்வு",
    multiChoiceDesc: "ஒன்றுக்கும் மேற்பட்டவற்றை தேர்ந்தெடுக்கலாம்",
    expiryTitle: "முடிவு நேரம்",
    expiryDesc: "குறிப்பிட்ட நேரத்தில் வாக்கெடுப்பு முடிவடையும்",
    privacyTitle: "பொதுவானதா / தனிப்பட்டதா",
    publicDesc: "அனைவரும் பார்க்கலாம்",
    privateDesc: "இணைப்பு உள்ளவர்கள் மட்டும்",
    publishBtn: "வெளியிடுக",
    myPolls: "என் வாக்கெடுப்புகள்",
    votedPolls: "வாக்களித்தவை",
    savedPolls: "சேமிக்கப்பட்டவை",
    totalVotesReceived: "மொத்த வாக்குகள்",
    participatedIn: "பங்கேற்றவை"
  },
  es: {
    brandName: "PollPulse",
    tagline: "Votaciones y Encuestas en Tiempo Real",
    heroBadge: "Plataforma de Encuestas en Tiempo Real con Prevención de Duplicados",
    heroTitle1: "Crea Encuestas. Reúne Voces.",
    heroTitle2: "Visualiza Resultados en Vivo.",
    heroDesc: "La plataforma todo en uno para toma de decisiones y votaciones. Gráficos interactivos, códigos QR y resultados en tiempo real.",
    createPoll: "Crear Encuesta",
    explorePolls: "Explorar Encuestas",
    trendingPolls: "Encuestas Populares",
    trendingDesc: "Las discusiones más activas ahora mismo",
    viewAll: "Ver Todas",
    totalPolls: "Total Encuestas",
    votesCast: "Votos Emitidos",
    activeNow: "Activas Ahora",
    registeredUsers: "Usuarios Registrados",
    noPollsFound: "No se encontraron encuestas.",
    whyChoose: "Diseñado para Votaciones Transparentes",
    whyDesc: "Todo lo que necesitas para encuestas seguras y sin manipulaciones.",
    antiDupTitle: "Sin Votos Duplicados",
    antiDupDesc: "Garantía de un solo voto por usuario.",
    liveUpdatesTitle: "Actualizaciones en Vivo",
    liveUpdatesDesc: "Cambios en tiempo real al instante vía WebSockets.",
    chartsTitle: "Gráficos Visuales",
    chartsDesc: "Gráficos de barras y donas interactivos.",
    qrTitle: "Códigos QR",
    qrDesc: "Comparte y vota desde el móvil escaneando el código QR.",
    navExplore: "Explorar",
    navCreate: "Crear",
    navDashboard: "Panel",
    navLogin: "Entrar",
    navRegister: "Registrarse",
    navLogout: "Salir",
    exploreTitle: "Encuestas de la Comunidad",
    exploreDesc: "Vota en diversos temas y mira qué opina la gente.",
    searchPlaceholder: "Buscar por título...",
    filterBy: "Filtrar por:",
    allPolls: "Todas",
    activeOnly: "Solo Activas",
    closedExpired: "Cerradas / Expiradas",
    sortBy: "Ordenar:",
    newestFirst: "Más Recientes",
    mostVoted: "Más Votadas",
    expiringSoon: "Por Expirar",
    catAll: "Todas",
    catTech: "Tecnología",
    catAI: "Inteligencia Artificial",
    catCareer: "Carrera y Trabajo",
    catGaming: "Videojuegos",
    catEntertainment: "Entretenimiento",
    catEducation: "Educación",
    catSports: "Deportes",
    catGeneral: "General",
    castYourVote: "Emite tu Voto",
    voteDistribution: "Distribución de Votos",
    submitVote: "Votar",
    logInToVote: "Inicia Sesión para Votar",
    votedBanner: "Tu voto ha sido registrado",
    yourChoice: "Tu Elección",
    closedBadge: "Cerrada",
    expiredBadge: "Expirada",
    noExpiry: "Sin Expiración",
    sharePoll: "Compartir",
    scanQR: "Escanear para Votar",
    copyLink: "Copiar Enlace",
    copied: "¡Copiado!",
    discussion: "Discusión de la Comunidad",
    postComment: "Publicar Comentario",
    commentPlaceholder: "Comparte tus razones...",
    noComments: "No hay comentarios aún.",
    like: "Me gusta",
    reactions: "Reacciones",
    exportData: "Exportar Datos",
    downloadCSV: "Descargar CSV",
    downloadJSON: "Descargar JSON",
    bookmark: "Guardar",
    bookmarked: "Guardado",
    createHeading: "Crear una Nueva Encuesta",
    createSubtitle: "Personaliza opciones, reglas y comparte.",
    pollDetailsStep: "1. Detalles",
    questionLabel: "Pregunta / Título",
    questionPlaceholder: "Ej. ¿Cuál es el mejor lenguaje en 2026?",
    descLabel: "Descripción (Opcional)",
    descPlaceholder: "Contexto adicional...",
    categoryLabel: "Categoría",
    optionsStep: "2. Opciones",
    addOption: "Añadir Opción",
    minOptionsHint: "Mínimo 2 opciones",
    settingsStep: "3. Configuración",
    multiChoice: "Permitir Opción Múltiple",
    multiChoiceDesc: "Los votantes pueden elegir más de una opción",
    expiryTitle: "Fecha de Expiración",
    expiryDesc: "Se cierra automáticamente al vencer el plazo",
    privacyTitle: "Pública vs Privada",
    publicDesc: "Visible en la sección explorar",
    privateDesc: "Solo accesible con enlace directo",
    publishBtn: "Publicar Encuesta",
    myPolls: "Mis Encuestas",
    votedPolls: "Encuestas Votadas",
    savedPolls: "Guardadas",
    totalVotesReceived: "Total Votos Recibidos",
    participatedIn: "Participaciones"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem("poll_lang") || "en");

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem("poll_lang", newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
